main/urls.py
# included in config.urls with prefix "main"
from django.urls import include, path, register_converter
from django.views.generic import TemplateView

import main.views as views

app_name = "main"

urlpatterns = [
    path("public_key/", views.public_key, name="public_key"),
    path("webhook/", views.webhook, name="webhook"),
    path("create-checkout-session/", 
         views.create_checkout_session, 
         name="create_checkout_session"),
    path("success/", 
         views.checkout_success,
         name="checkout_success"),
    path("cancel_checkout/",
         TemplateView.as_view(template_name="main/cancel.html"),
         name="checkout_cancel"),
     path("payment/",
          views.payment,
          name="payment"),
     path("cancel_subscription/",
          views.cancel_subscription,
          name="cancel_subscription"),
     path("reactivate/",
          views.reactivate_subscription,
          name="reactivate_subscription"),
     path("expired/",
          TemplateView.as_view(template_name="main/expired.html"),
          name="expired"),
     path("processing/",
          TemplateView.as_view(template_name="main/processing.html"),
          name="processing"),
    ]

nnr/users/urls.py
from django.urls import path

from nnr.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

from main.views import (
    update_payment,
    confirm_payment
)

from recipes.views import (
    SavedRecipeList,
    SubmittedRecipeList,
    RatedRecipeList,
    UserTagList,
    UserTagDetail,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~update_payment",
        view=update_payment,
        name="update_payment"),
    path("~confirm_payment",
         view=confirm_payment, 
         name="confirm_payment"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/saved/", 
        view=SavedRecipeList.as_view(), 
        name="saved_recipes"),
    path("<str:username>/submitted/", 
        view=SubmittedRecipeList.as_view(), 
        name="submitted_recipes"),
    path("<str:username>/rated/",
        view=RatedRecipeList.as_view(),
        name="rated_recipes"),
    path("<str:username>/tagged/",
        view=UserTagList.as_view(),
        name="user_tags"),
    path("<str:username>/tagged/<str:tag_slug>/",
        view=UserTagDetail.as_view(),
        name="usertag_detail"),        

]

recipes/urls.py
# Recipes urls. Imported with no prefix
from django.urls import include, path, register_converter
import recipes.views as views
import recipes.converters as converters

app_name = "recipes"

register_converter(converters.LetterConverter, "letter")

recipe_urls = [
     path("browse", 
          view=views.RecipeList.as_view(),
          name="recipe_list"),
     path("add/",
          view=views.CreateRecipe.as_view(),
          name="recipe_create"),
     path("edit/<slug:slug>/",
          view=views.UpdateRecipe.as_view(),
          name="recipe_update"),
     path("delete/<slug:slug>/",
         view=views.DeleteRecipe.as_view(),
         name="recipe_delete"),         
     path("save/",
          view=views.SaveRecipe.as_view(),
          name="save_recipe"),         
     path("rate/",
          view=views.RateRecipe.as_view(),
          name="rate_recipe"),
     path("search/",
          view=views.SearchRecipes.as_view(),
          name="search_recipes"),
     path("<letter:first_letter>/",
          view=views.RecipeByLetterList.as_view(),
          name="letter_recipe"),
     path("<slug:slug>/",
          view=views.RecipeDetail.as_view(),
          name="recipe_detail"),         
]

tag_urls = [
     path("",
          view=views.TagList.as_view(),
          name="tag_list"),
     path("tagrecipe/",
          view=views.TagRecipe.as_view(),
          name="tag_recipe"),
     path("untag/",
          view=views.untag,
          name="untag"),
     path("all/",
          view=views.all_tags,
          name="get_all_tags"),
     path("<slug:slug>",
          view=views.TagDetail.as_view(),
          name="tag_detail"),
]

urlpatterns = [
    path("rotd/", 
          view=views.RecipeOfTheDay.as_view(),
          name="rotd"),
     path("home/",
          view=views.DashboardView.as_view(),
          name="home"),
    path("tags/", include(tag_urls)),
    path("", include(recipe_urls)),    
]

nnr/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

nnr/users/views.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

import stripe

from main.forms import CancelForm, ReactivateForm
User = get_user_model()

class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        
        context =  super().get_context_data(**kwargs)
        subs = None
        has_sub = not self.object.profile.subscription_status in ("admin", "free", "")
        if has_sub:
            stripe.api_key = settings.STRIPE_SK
            subs = stripe.Subscription.list(customer=self.object.profile.stripe_id)
        context["has_sub"] = has_sub
        if subs:
            context["cancel_at_period_end"] = subs.data[0].cancel_at_period_end
            end_date = datetime.fromtimestamp(subs.data[0].current_period_end)
            context["subscription_end"] = end_date.strftime("%B %d, %Y")
            context["amount"] = subs.data[0].plan.amount / 100
            context["cancel_form"] = CancelForm()
            context["reactivate_form"] = ReactivateForm()
        return context

user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]
    context_object_name = "user"

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

recipes/views.py
import json
import pickle

from operator import itemgetter

from crispy_forms.layout import Submit

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.postgres.search import (SearchQuery, 
                                            SearchRank, 
                                            SearchVector)
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator                                        
from django.db.models import Avg, Count
from django.http import JsonResponse
from django.middleware.csrf import get_token
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import (CreateView, UpdateView, DeleteView, ListView,
                                  DetailView, FormView, TemplateView) 

from mixins import ValidUserMixin, RateLimitMixin

from comments.forms import CreateCommentForm
from decorators import user_is_valid_api
from recipes.forms import (CreateRecipeForm, UpdateRecipeForm, TagRecipeForm,
                           SaveRecipeForm, RateRecipeForm, RecipeSearchForm,
                           UntagRecipeForm)
                           

from recipes.models import (Recipe, Tag, UserTag, RecipeRating, 
                            LetterCount, make_detail_key)

import logging                            

User = get_user_model()                                                    

logger = logging.getLogger(__name__)


class CreateRecipe(ValidUserMixin, RateLimitMixin, CreateView):
    model = Recipe
    form_class = CreateRecipeForm
    
    def get_initial(self):
        initial = super().get_initial()
        initial["user"] = self.request.user
        return initial
        

class RecipeDetail(DetailView):
    model = Recipe
    slug_field = "title_slug"
    context_object_name = "recipe"

    def get_object(self, queryset=None):
        slug = self.kwargs["slug"]
        recipe_key = make_detail_key(slug)
        self.object = cache.get(recipe_key)
        if not self.object:
            logger.info(f"Cache miss: {recipe_key}")
            self.object = get_object_or_404(Recipe, title_slug=slug)
            cache.set(recipe_key, self.object, 60*60*24)
        else:
            logger.info(f"Cache hit: {recipe_key}")
        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        tags = (self.object.usertag_set
                    .values("tag__name", "tag__name_slug")
                    .annotate(Count("tag"))
                    .order_by("-tag__count"))

        if self.request.user.is_authenticated:
            # For authenticated users show comments, comment form, tags they've added
            # untag, add tags, save/unsave, submit ratings

            # Comments
            comment_form = CreateCommentForm(initial={"user": self.request.user,
                                                    "recipe": self.object})
            context["comment_form"] = comment_form

            # Tags for logged in users
            user_slugs = {tag.name_slug for tag
                        in Tag.objects.filter(usertag__user=self.request.user,
                                                recipe=self.object)}
            if tags:
                def add_untag_form(tag_slug):
                    if (tag_slug in user_slugs and 
                        self.request.user.is_authenticated):
                        return UntagRecipeForm(initial={"tag_slug": tag_slug,
                                                        "recipe": self.object})
                    else:
                        return None

                tag_list = [{"name": tag["tag__name"],
                            "slug": tag["tag__name_slug"],
                            "count": tag["tag__count"],
                            "untag_form": add_untag_form(tag["tag__name_slug"])}
                            for tag in tags]

                # Put user's own tags first (ones that have option to untag)
                tag_list.sort(key=lambda x : x["untag_form"] is None)
            else:
                tag_list = []

            context["tagform"] = TagRecipeForm(initial={"user": self.request.user,
                                                        "recipe": self.object})

            # Save / Unsave                                                        
            saveform = SaveRecipeForm(initial={"user": self.request.user,
                                            "recipe": self.object})                                                        
            if self.object in self.request.user.profile.saved_recipes.all():
                btn = "Unsave"
                css = "btn btn-outline-primary btn-sm"
            else:
                btn = "Save"
                css = "btn btn-primary btn-sm"
            submit = Submit(btn, btn)
            submit.field_classes=css
            saveform.helper.add_input(submit)
            context["saveform"] = saveform

            # Rating form
            rate_initial = {"user": self.request.user,
                            "recipe": self.object}
            try:
                rr = RecipeRating.objects.get(recipe=self.object,
                                                user=self.request.user)
                rate_initial["rating"] = rr.rating
            except RecipeRating.DoesNotExist:
                pass

            context["rateform"] = RateRecipeForm(initial=rate_initial)

        else:
            # Users not logged in get tags only
            tag_list = [{"name": tag["tag__name"],
                         "slug": tag["tag__name_slug"],
                         "count": tag["tag__count"]} for tag in tags]
                            

        # Everyone gets a list of tags and the recipe rating        
        context["tag_list"] = tag_list

        context["average_rating"] = RecipeRating.objects.\
                                    filter(recipe=self.object).\
                                    aggregate(Avg("rating"))["rating__avg"]
        return context


class RecipeOfTheDay(DetailView):
    model = Recipe
    context_object_name = "recipe"
    template_name = "recipes/rotd.html"

    def get_object(self, queryset=None):
        try:
            obj = Recipe.objects.get(featured=True)
        except Recipe.DoesNotExist:
            obj = None
        return obj


class RecipeList(ListView):
    model = Recipe
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lettercounts"] = LetterCount.objects.all()
        context["title"] = "All Recipes"
        return context        


class UpdateRecipe(UserPassesTestMixin, UpdateView):
    model = Recipe
    form_class = UpdateRecipeForm
    slug_field = "title_slug"

    def test_func(self):
        self.object = self.get_object()
        return (self.request.user.is_staff or 
                self.request.user == self.object.user)        

    
class DeleteRecipe(UserPassesTestMixin, DeleteView):
    model = Recipe
    success_url = reverse_lazy("recipes:recipe_list")
    slug_field = "title_slug"

    def test_func(self):
        self.object = self.get_object()
        return (self.request.user.is_staff or
                self.request.user == self.object.user)


class TagList(ListView):
    model = Tag
    paginate_by = 150

    def get_queryset(self):
        qs = (Tag.objects.annotate(ut_count=Count("usertag"))
                         .filter(ut_count__gt=0))
        return qs


class TagDetail(ListView):
    model = Recipe
    slug_field = "name_slug"
    paginate_by = 50
    template_name = "recipes/tag_detail.html"

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, name_slug=self.kwargs["slug"])
        qs = Recipe.objects.filter(usertag__tag=self.tag).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        return context    

class UserTagList(ValidUserMixin, ListView):
    model = Tag
    paginate_by = 144
    template_name = "users/usertag_list.html"

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, 
                                              username=self.kwargs["username"])
        qs = Tag.objects.filter(usertag__user=self.profile_user).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["profile_user"] = self.profile_user
        return context

class UserTagDetail(ValidUserMixin, ListView):
    model = Recipe
    paginate_by = 50
    template_name = "users/usertag_detail.html"

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, 
                                              username=self.kwargs["username"])
        self.tag = get_object_or_404(Tag, name_slug=self.kwargs["tag_slug"])
        qs = Recipe.objects.filter(usertag__tag=self.tag,
                                   usertag__user=self.profile_user).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        context["profile_user"] = self.profile_user
        return context


class TagRecipe(ValidUserMixin, FormView):
    form_class = TagRecipeForm

    def form_valid(self, form):
        form.save_tags()
        kw = {"slug": form.cleaned_data["recipe"].title_slug}
        return redirect(reverse_lazy("recipes:recipe_detail", kwargs=kw))        

@user_is_valid_api
@require_POST
def untag(request):

nnr/templates/recipes/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="main-content">
    <div class="row">
        <div class="col-lg-6">
            <h3>Recently added</h3>
            {% with object_list=recent %}
            {% include "recipes/recipe_ul.html" %}
            {% endwith %}
        </div>
        <div class="col-lg-6">
            <h3>Highest Rated</h3>
            {% with object_list=highest %}
            {% include "recipes/recipe_ul.html" %}
            {% endwith %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
        <h3>Your saved recipes</h3>
        {% with object_list=saved empty_text=saved_none %}
        {% include "recipes/recipe_ul.html" %}
        {% endwith %}
        {% if saved %}
        <p><a href="{% url 'users:saved_recipes' request.user.username %}">View all saved recipes</a></p>
        {% endif %}
        </div>
        <div class="col-lg-6">
        <h3>Your Tags</h3>
        <p>
            {% for tag in user_tags  %}
            <a href="{% url 'users:usertag_detail' request.user.username tag.name_slug %}"
               title="You have {{ tag.numtags }} recipes with this tag">{{ tag.name }}</a>{% if not forloop.last %}, {% else %}...{% endif %}
            {% empty %}
            Looks like you haven't tagged any recipes yet. Try adding some tags
            to recipes you like using the form at the bottom of the recipe page
            to organize your favorites!
            {% endfor %}
        </p>
        {% if user_tags %}
        <p><a href="{% url 'users:user_tags' request.user.username %}">View all tags</a></p>
        {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

nnr/templates/recipes/pagination.html
{% load main_extra %}
<nav aria-label="page navigation">
    <ul class="pagination pagination-sm justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{{ request|add_page_num:'1'}}">&laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ request|add_page_num:page_obj.previous_page_number }}">previous</a>
        </li>            
        {% endif %}
        {% for page_number in page_obj.number|page_window:page_obj.paginator.num_pages  %}
        <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
            <a class="page-link" href="{{ request|add_page_num:page_number }}">
                {{ page_number }} 
                {% if page_number == page_obj.number %}
                of {{ page_obj.paginator.num_pages }}
                {% endif %}
            </a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ request|add_page_num:page_obj.next_page_number }}">next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ request|add_page_num:page_obj.paginator.num_pages }}">last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>

nnr/templates/recipes/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container main-content">
    <form method="POST">
    {% csrf_token %}
    <p>Really delete {{ object.title }}?</p>
    <a href="{% url 'recipes:recipe_list' %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" class="btn btn-danger" value="Delete" />
</form>
{% endblock content %}

nnr/templates/recipes/recipe_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/comments.css' %}" rel="stylesheet">
<link href="{% static 'css/nnr_autocomplete.css' %}" rel="stylesheet">
<meta name="user_id" content="{{ request.user.id }}">
<meta name="recipe_id" content="{{ recipe.id }}">

<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Recipe",
    "name": "{{ recipe.title }}",
    "datePublished": "{{ recipe.created_dt|date:'Y-m-d' }}",
    "recipeIngredient": [
        {% for line in recipe.ingredients_list %}
        "{{ line }}"{% if not forloop.last %},{% endif %}
        {% endfor %}
    ],
    "recipeInstructions": [
        {{ recipe.get_instructions_text }}
    ]
}
</script>
{% endblock morecss %}


{% block title %}
{{ recipe.title }}
{% endblock %}


{% block content %}
<div class="container main-content">

    <h1>{{ recipe.title }}</h1>
    <div class="byline">
        Submitted by: 
        {% if recipe.user %}
        <a href="{% url 'users:detail' recipe.user.username %}">{{ recipe.user.username }}</a>
        {% else %}
        <em>deleted</em>
        {% endif %}
        on {{ recipe.created_dt|date:"F j, Y" }}
    </div>
    <div class="quantity recipe-section">
        {{ recipe.quantity_html|safe }}
    </div>
    
    <h2>Ingredients</h2>
    <div class="ingredients">
        {{ recipe.ingredients_html|safe }}
    </div>
    <h2>Instructions</h2>
    <div class="instructions">
        {{ recipe.instructions_html|safe }}
    </div>

    {% if recipe.see_also.count > 0 %}
    <h3>Related Recipes</h3>
    <div class="recipe-section">
        {% for related in recipe.see_also.all %}
        <a href="{% url 'recipes:recipe_detail' related.title_slug %}">{{ related.title }}</a>{% if not forloop.last %};{% endif %} 
        {% endfor %}
    </div>
    {% endif %}

    <div class="user-options row recipe-section">
        <div class="col-sm-2">
            {% if average_rating %}
            {{ average_rating }} ⭐ avg.
            {% endif %}
        </div>
        {% if request.user.is_authenticated %}
        <div class="col-sm-4">
            {% crispy rateform %}
        </div>
        
        <div class="col-sm-2">
            {% crispy saveform %}
        </div>
        {% endif %}
        {% if recipe.user == request.user or request.user.is_staff %}
        <div class="col-sm-4">
            <a href="{% url 'recipes:recipe_update' recipe.title_slug %}" class="btn btn-primary btn-sm">Edit</a>
            <a href="{% url 'recipes:recipe_delete' recipe.title_slug %}" class="btn btn-danger btn-sm">Delete</a>
        </div>
        {% endif %}
    </div>



    <div class="tags recipe-section">
        <h2>Tags</h2>
        <div id="tag-container">
            {% for tag in tag_list %}
            <a href="{% url 'recipes:tag_detail' tag.slug %}" 
               title="{{ tag.count }} user{{ tag.count|pluralize }} tagged this recipe as {{ tag.name }}">
                {{ tag.name }}</a>{% if tag.untag_form %}{% include 'recipes/usertag_delete.html' %}{% endif %}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </div>
        {% if request.user.is_authenticated %}
            {% crispy tagform %}
            <small class="form-text text-muted">{{ tagform.fields.tags.help_text }}</small>
        {% endif %}
    </div>
    {% if request.user.is_authenticated %}
        {% include 'comment_container.html' %}
    {% endif %}

    {% if not request.user.is_authenticated %}
    <div class="alert-success p-3 border border-success rounded">
        <h2>Hi There!</h2>
        <p>
            Thanks for using No Nonsense Recipes. We strive to make it a pleasant experience. You won't find ads or long, boring stories here. If you're enjoying the site, consider <a href="{% url 'account_signup' %}">signing up</a> for an account. You will be supporting the project and gaining access to additional awesome features, such as:
        </p>
        <ul class="list-unstyled">
            <li class="font-weight-bold">Search recipes</li>
            <li class="font-weight-bold">Submit your own recipes</li>
            <li class="font-weight-bold">View and make comments on recipes</li>
            <li class="font-weight-bold">Rate recipes</li>
            <li class="font-weight-bold">Save and tag recipes to quickly find them later</li>
        </ul>

        <p> 
            Accounts are free for 30 days and then only $19 USD per year or $2.57 per month. What have you got to lose? 😃 
        </p>
        <p>
            <a class="btn btn-success" href="{% url 'account_signup' %}">Start your Free Trial</a> today!
        </p>
    </div>
    {% endif %}

    
</div>
{% endblock %}



{% block morejs %}
    {% if request.user.is_authenticated %}
    <script src="{% static 'js/comments.js' %}"></script>
    <script src="{% static 'js/tags.js' %}"></script>
    {% endif %}
{% endblock morejs %}

nnr/templates/recipes/recipe_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load cache %}
{% load main_extra %}

{% block title %}
{{ title }}
{% endblock %}


{% block content %}
<div class="main-content">
<h1>{{ title }}</h1>
    <nav id="letter-nav" aria-label="letter navigation">
        <ul class="pagination pagination-sm">
            <li class="page-item">
                <a class="page-link" href="{% url 'recipes:tag_list' %}">Tags</a>
            </li>
            {% cache 604800 lettercounts request.path|path_to_key %}
            {% for lc in lettercounts %}
            <li class="page-item {% if lc.quantity < 1 %}disabled{% endif %}{% if lc.letter == current %}active{% endif %}">
                <a class="page-link" href="{% url 'recipes:letter_recipe' lc.letter %}">
                    {{ lc.letter }}
                </a>
            </li>
            {% endfor %}
            {% endcache %}
        </ul>
    </nav>
    <div class="main-list">
        {% cache 3600 recipe_list request.path page_obj.number %}
        {% include "recipes/recipe_ul.html" %}
        {% endcache %}
    </div>
    {% include "recipes/pagination.html" %}
</div>
{% endblock %}

nnr/templates/recipes/recipe_ul.html
<ul class="list-group recipe-list">
    {% for recipe in object_list %}
    <li class="list-group-item">
        <a href="{% url 'recipes:recipe_detail' recipe.title_slug %}">{{ recipe.title }}</a>
    </li>
    {% empty %}
    <li class="list-group-item">
        {{ empty_text|default:"No Recipes Found" }}
    </li>
    {% endfor %}
</ul>

nnr/templates/recipes/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}
{{ title|default:"Search" }}
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="search-form">
        {% crispy form %}
    </div>
    {% if terms %}
    <h2>Search Results</h2>
    {% endif %}
    {% if tag_results %}
    <h3>Tags related to "{{ terms }}":</h3>
    <p>
        {% for tag in tag_results  %}<a href="{% url 'recipes:tag_detail' tag.name_slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
    </p>
    {% endif %}
    {% if terms %}    
    <h3>{{ title|default:"Recipes related to" }} "{{ terms }}"</h3>
    <p>Found {{ page_obj.paginator.count|intcomma }} recipes</p>
    {% with object_list=page_obj.object_list %}
    <div class="main-list">
        {% include "recipes/recipe_ul.html" %}
    </div>
    {% endwith %}
    {% include "recipes/pagination.html" %}
    {% endif %}
</div>
{% endblock %}

nnr/templates/recipes/tag_detail.html
{% extends "base.html" %}

{% block title %}
{{ tag.name }}
{% endblock %}

{% block content %}
<div class="main-content">
    <h1>Recipes tagged {{ tag.name }}</h1>
    <p class="small"><a href="{% url 'recipes:tag_list' %}">&laquo; Back to Tag List</a></p>
    {% include "recipes/recipe_ul.html" %}
    {% include "recipes/pagination.html" %}
</div>
{% endblock %}

nnr/templates/recipes/tag_list.html
{% extends "base.html" %}

{% block title %}
Tags
{% endblock %}


{% block content %}
<div class="main-content">
    <h1>Tags</h1>
    <div class="main-list">
        <div class="row no-gutters">
            {% for tag in object_list %}
            <div class="col-sm-2 text-center mr-1 mb-1 align-middle">
                <a class="btn btn-outline-info" href="{% url 'recipes:tag_detail' tag.name_slug %}">{{ tag }}</a>
            </div>
            {% if forloop.counter|divisibleby:5 %}
            </div>
            <div class="row no-gutters">
            {% endif %}
            {% empty %}
            <p>No tags found</p>
            {% endfor %}
        </div>
    </div>
    {% include "recipes/pagination.html" %}
</div>
{% endblock %}

nnr/templates/recipes/usertag_delete.html
{% load static %}
<div class="untag-container" id="untag-container_{{ tag.slug }}">
    <a id="untag_link_{{ tag.slug }}" href="#" class="untag-link" data-toggle="modal" data-target="#untag_{{ tag.slug }}">
        <img src="{% static 'images/delete.svg' %}" width="14px" height="14px" />
    </a>
    <div id="untag_{{ tag.slug }}"class="modal" tagindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Remove Tag</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Remove your tag <span class="your-tag">{{ tag.name }}</span> from this recipe?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'recipes:untag' %}" class="untag-form">
                        {% csrf_token %}
                        {% for field in tag.untag_form  %}
                        {{ field }}
                        {% endfor %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input type="submit" class="btn btn-danger" value="Remove Tag">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>