main/urls.py
# included in config.urls with prefix "main"
from django.urls import include, path, register_converter
from django.views.generic import TemplateView

import main.views as views

app_name = "main"

urlpatterns = [
    path("public_key/", views.public_key, name="public_key"),
    path("webhook/", views.webhook, name="webhook"),
    path("create-checkout-session/", 
         views.create_checkout_session, 
         name="create_checkout_session"),
    path("success/", 
         views.checkout_success,
         name="checkout_success"),
    path("cancel_checkout/",
         TemplateView.as_view(template_name="main/cancel.html"),
         name="checkout_cancel"),
     path("payment/",
          views.payment,
          name="payment"),
     path("cancel_subscription/",
          views.cancel_subscription,
          name="cancel_subscription"),
     path("reactivate/",
          views.reactivate_subscription,
          name="reactivate_subscription"),
     path("expired/",
          TemplateView.as_view(template_name="main/expired.html"),
          name="expired"),
     path("processing/",
          TemplateView.as_view(template_name="main/processing.html"),
          name="processing"),
    ]

nnr/users/urls.py
from django.urls import path

from nnr.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

from main.views import (
    update_payment,
    confirm_payment
)

from recipes.views import (
    SavedRecipeList,
    SubmittedRecipeList,
    RatedRecipeList,
    UserTagList,
    UserTagDetail,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~update_payment",
        view=update_payment,
        name="update_payment"),
    path("~confirm_payment",
         view=confirm_payment, 
         name="confirm_payment"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/saved/", 
        view=SavedRecipeList.as_view(), 
        name="saved_recipes"),
    path("<str:username>/submitted/", 
        view=SubmittedRecipeList.as_view(), 
        name="submitted_recipes"),
    path("<str:username>/rated/",
        view=RatedRecipeList.as_view(),
        name="rated_recipes"),
    path("<str:username>/tagged/",
        view=UserTagList.as_view(),
        name="user_tags"),
    path("<str:username>/tagged/<str:tag_slug>/",
        view=UserTagDetail.as_view(),
        name="usertag_detail"),        

]

recipes/urls.py
# Recipes urls. Imported with no prefix
from django.urls import include, path, register_converter
import recipes.views as views
import recipes.converters as converters

app_name = "recipes"

register_converter(converters.LetterConverter, "letter")

recipe_urls = [
     path("browse", 
          view=views.RecipeList.as_view(),
          name="recipe_list"),
     path("add/",
          view=views.CreateRecipe.as_view(),
          name="recipe_create"),
     path("edit/<slug:slug>/",
          view=views.UpdateRecipe.as_view(),
          name="recipe_update"),
     path("delete/<slug:slug>/",
         view=views.DeleteRecipe.as_view(),
         name="recipe_delete"),         
     path("save/",
          view=views.SaveRecipe.as_view(),
          name="save_recipe"),         
     path("rate/",
          view=views.RateRecipe.as_view(),
          name="rate_recipe"),
     path("search/",
          view=views.SearchRecipes.as_view(),
          name="search_recipes"),
     path("<letter:first_letter>/",
          view=views.RecipeByLetterList.as_view(),
          name="letter_recipe"),
     path("<slug:slug>/",
          view=views.RecipeDetail.as_view(),
          name="recipe_detail"),         
]

tag_urls = [
     path("",
          view=views.TagList.as_view(),
          name="tag_list"),
     path("tagrecipe/",
          view=views.TagRecipe.as_view(),
          name="tag_recipe"),
     path("untag/",
          view=views.untag,
          name="untag"),
     path("all/",
          view=views.all_tags,
          name="get_all_tags"),
     path("<slug:slug>",
          view=views.TagDetail.as_view(),
          name="tag_detail"),
]

urlpatterns = [
    path("rotd/", 
          view=views.RecipeOfTheDay.as_view(),
          name="rotd"),
     path("home/",
          view=views.DashboardView.as_view(),
          name="home"),
    path("tags/", include(tag_urls)),
    path("", include(recipe_urls)),    
]

main/models.py
from dateutil.relativedelta import relativedelta
import stripe

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

import datetime
import logging

UTC = datetime.timezone.utc
BASE_RATE = 30 if settings.DEBUG else 5

logger = logging.getLogger(__name__)

def next_year():
    today = datetime.date.today()
    return today + relativedelta(years=+1)

def get_basic_plan():
    plan, _ =  PaymentPlan.objects.get_or_create(name_slug="basic", 
                                                 defaults={"name": "Basic"})
    return plan.id

PAYMENT_STATUS = ((0, "FAILED"),
                  (1, "NEEDS CONFIRMATION"),
                  (2, "TRIAL"),
                  (3, "SUCCESS"),
                  (4, "PENDING"),
                  (5, "CANCELED"))

SUBSCRIPTION_STATUS = (
    ("", "undefined"),
    ("admin", "Administrator"),
    ("free", "Free Account"),
    ("incomplete", "Incomplete"),
    ("incomplete_expired", "Incomplete, Session Expired"),
    ("trialing", "Free Trial"),
    ("active", "Active"),
    ("past_due", "Past Due"),
    ("canceled", "Canceled"),
    ("unpaid", "Unpaid")
)                  
                  
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    plan = models.ForeignKey("PaymentPlan", 
                             on_delete=models.SET_DEFAULT, 
                             default=get_basic_plan)
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    next_payment = models.DateField(_("Next Payment"), default=next_year)
    saved_recipes = models.ManyToManyField("recipes.Recipe", 
                                           related_name="saved_by")
    stripe_id = models.CharField(_("Stripe Customer Id"), max_length=50, 
                                 default="")
    checkout_session = models.CharField(_("Stripe Checkout Session"), max_length=100, 
                                        default="")
    payment_status = models.PositiveSmallIntegerField(_("Payment Status"), 
                                                      choices=PAYMENT_STATUS,
                                                      default=4)
    subscription_status = models.CharField(_("Subscription Status"), 
                                           max_length=25,
                                           default="",
                                           choices=SUBSCRIPTION_STATUS)
    subscription_end = models.DateField(_("Subscription End"))
    rate_level = models.PositiveSmallIntegerField(_("Rate Level"),
                                                  default=1)
    last_sub = models.DateTimeField(_("Last Submission"), 
                                    default=datetime.datetime(year=1970,
                                                              month=1,
                                                              day=1,
                                                              tzinfo=UTC))
    
    
    def __str__(self):
        return f"{self.user.username} ({self.user.id})"

    def is_valid(self):
        return self.subscription_status in ("admin", 
                                            "free", 
                                            "trialing", 
                                            "active")

    def paid(self):
        return self.subscription_status in ("admin", 
                                            "free", 
                                            "active")

    def rate_limit_exceeded(self):
        now = datetime.datetime.now(tz=UTC)
        limit = BASE_RATE ** self.rate_level
        diff = now - self.last_sub
        exceeded = diff.total_seconds() < limit
        if exceeded:
            # submission is too soon after the last one
            self.rate_level += 1
            msg = (f"Posting too fast. Try again in "
                   f"{BASE_RATE ** self.rate_level} seconds.")
        else:
            self.rate_level = 1
            msg = ""
        self.last_sub = now
        self.save()
        
        return exceeded, msg
    
    def reset_rate_limit(self):
        self.rate_level = 1
        self.save()

    def sync_subscription(self):
        stripe.api_key = settings.STRIPE_SK
        if self.stripe_id:
            subs = stripe.Subscription.list(customer=self.stripe_id)
            if subs.data:
                self.subscription_status = subs.data[0].status
            else:
                self.subscription_status = "canceled"
        elif self.checkout_session:
            self.subscription_status = "incomplete"
        elif self.user.is_staff or self.user.is_superuser:
            self.subscription_status = "admin"
        else:
            self.subscription_status = "free"
        self.save()

    def update_stripe_id(self):
        stripe.api_key = settings.STRIPE_SK
        if not self.stripe_id:
            result = stripe.Customer.list(email=self.user.email, limit=1)
            if result.data:
                self.stripe_id = result.data[0].id
                self.save()

            

class PaymentPlan(models.Model):
    name = models.CharField(_("Name"), max_length=25)
    name_slug = models.SlugField(_("Name Slug"), max_length=25, unique=True)
    interval = models.PositiveSmallIntegerField(_("Days between payments"), default=365)
    amount = models.PositiveSmallIntegerField(_("Amount"), default=10)
    stripe_id = models.CharField(_("Stripe Plan Id"), max_length=50,
                                 default="")

    class Meta:
        ordering = ["name_slug"]

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"

nnr/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

nnr/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

nnr/users/views.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

import stripe

from main.forms import CancelForm, ReactivateForm
User = get_user_model()

class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        
        context =  super().get_context_data(**kwargs)
        subs = None
        has_sub = not self.object.profile.subscription_status in ("admin", "free", "")
        if has_sub:
            stripe.api_key = settings.STRIPE_SK
            subs = stripe.Subscription.list(customer=self.object.profile.stripe_id)
        context["has_sub"] = has_sub
        if subs:
            context["cancel_at_period_end"] = subs.data[0].cancel_at_period_end
            end_date = datetime.fromtimestamp(subs.data[0].current_period_end)
            context["subscription_end"] = end_date.strftime("%B %d, %Y")
            context["amount"] = subs.data[0].plan.amount / 100
            context["cancel_form"] = CancelForm()
            context["reactivate_form"] = ReactivateForm()
        return context

user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]
    context_object_name = "user"

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

nnr/templates/users/confirm_payment.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}
Confirm Payment Information
{% endblock title %}

{% block user_content %}
<h2>Confirm Payment Information</h2>
<p>Your credit card requires an additional step to confirm your payment
information. Please follow the link below to complete the payment
confirmation.</p>
<a href="{{ invoice_url }}" class="btn btn-primary">Confirm Payment</a>
{% endblock user_content %}     

{% block morejs %}

{% endblock morejs %}

nnr/templates/users/rated_recipes.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}Submitted Recipes{% endblock %}


{% block user_content  %}
<h1>Rated Recipes</h1>
<div class="main-list">
    <ul class="list-group recipe-list">
        {% for rating in object_list %}
        <li class="list-group-item">
            <a href="{% url 'recipes:recipe_detail' rating.recipe.title_slug %}">
                {{ rating.recipe.title }}
            </a>
            <span class="float-right">{{ rating.get_rating_display }}</span>
        </li>
        {% empty %}
        <li class="list-group-item">
            No recipes rated yet.
        </li>
        {% endfor %}
    </ul>        
</div>
{% include "recipes/pagination.html" %}
    
{% endblock user_content %}

nnr/templates/users/saved_recipes.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}Saved Recipes{% endblock %}


{% block user_content  %}
<h1>Saved Recipes</h1>
<div class="main-list">
    {% include "recipes/recipe_ul.html" %}
</div>
{% include "recipes/pagination.html" %}
    
{% endblock user_content %}

nnr/templates/users/submitted_recipes.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}Submitted Recipes{% endblock %}


{% block user_content  %}
<h1>Submitted Recipes</h1>
<div class="main-list">
    {% include "recipes/recipe_ul.html" %}
</div>
{% include "recipes/pagination.html" %}
    
{% endblock user_content %}

nnr/templates/users/update_payment.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}
Update Payment Information
{% endblock title %}

{% block user_content %}
<div class="user-content">
    <h2>Current Payment Method</h2>
    {% for pm in payment_methods  %}
    <div class="row" style="margin-bottom: 10px;">
        <div class="col-sm-7" id="card_info">
            {{ pm.card.brand|capfirst }} ending with {{ pm.card.last4 }} exp {{ pm.card.exp_month}}/{{ pm.card.exp_year}}
        </div>
        <div class="col-sm-2">
            {% if pm.id == customer.invoice_settings.default_payment_method %}
            <span class="default_pm">Default</span> 
            {% endif %}
        </div>
    </div>
    {% empty %}
    <p>No payment methods found</p>
    {% endfor %}

    <h2 id="update_payment_header">Update Payment Information</h2>

    <form id="update_payment" class="update_payment" action="{% url 'users:update_payment' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div id="card-element"></div>
            <div id="card-errors"></div>
        </div>
        <div style="display: flex; flex-direction: column; align-items: flex-start;">
            <input type="submit" id="submit-id-update_payment" class="btn btn-primary" name="update" value="Update">
        </div>
    </form>
</div>
{% endblock user_content %}     

{% block morejs %}
<script type="text/javascript" src="{% static 'js/update_payment.js' %}"></script>
{% endblock morejs %}

nnr/templates/users/user_base.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}
<div class="user-main">
    <div class="row">
        <div class="col-lg-2 bg-light">
            <ul class="nav flex-column">
                <li class="nav-item">
                    Recipes
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:submitted_recipes' user.username %}">Submitted</a>
                        </li>                 
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:user_tags' user.username %}">Tagged</a>
                        </li>                        
                        {% if  request.user == user %}   
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:saved_recipes' user.username %}">Saved</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:rated_recipes' user.username %}">Rated</a>
                        </li>
                        
                        {% endif %}
                    </ul>
                </li>
                {% if request.user == user %}
                <li class="nav-item">
                    Account
                    <ul class="nav flex-column">
                        {% comment %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'users:update' %}">My Info</a>
                        </li>
                        {% endcomment %}                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_email' %}">E-Mail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:update_payment' %}">Payment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_change_password' %}">Password</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="col-lg-8">
            <div id="user-content">
            {% block user_content  %}
            {% endblock user_content %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

nnr/templates/users/user_detail.html
{% extends "users/user_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block user_content %}
  <h2>{{ user.username }}</h2>
  {% if user.name %}
    <p>{{ user.name }}</p>
  {% endif %}

  {% if request.user == user %}

    <p>Subscription status: {{ user.profile.get_subscription_status_display }}</p>

    {% if has_sub %}
      {% if cancel_at_period_end %}
      <p>Your subscription will expire on {{ subscription_end }}. You will not be charged.</p>
      {% crispy reactivate_form %}
      {% else %}
      <p>Your subscription will automatically be renewed for ${{ amount|floatformat:2 }} USD on {{ subscription_end }}.</p>
      {% crispy cancel_form %}
      {% endif %}
    {% endif %}

  {% endif %}

{% endblock user_content %}

nnr/templates/users/user_form.html
{% extends "account/base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block inner %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

nnr/templates/users/usertag_detail.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}Recipes {{ profile_user.username }} tagged "{{ tag }}"{% endblock %}


{% block user_content  %}
<h1>Recipes {{ profile_user.username }} tagged "{{ tag }}"</h1>
<div class="main-list">
    {% include "recipes/recipe_ul.html" %}
</div>
{% include "recipes/pagination.html" %}
    
{% endblock user_content %}

nnr/templates/users/usertag_list.html
{% extends "users/user_base.html" %}
{% load static %}

{% block title %}{{ profile_user.username }}'s Tags{% endblock %}


{% block user_content  %}
<h1>{{ profile_user.username }}'s Tags</h1>
<div class="main-list">
    <div class="row">
            {% for tag in object_list %}
            <div class="col-sm-2">
                <a href="{% url 'users:usertag_detail' profile_user.username tag.name_slug %}">{{ tag }}</a>
            </div>
            {% if forloop.counter|divisibleby:6 %}
            </div>
            <div class="row">
            {% endif %}
            {% empty %}
            <p>No tags found</p>
            {% endfor %}
        </div>
</div>
{% include "recipes/pagination.html" %}
    
{% endblock user_content %}