config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from recipes.models import Recipe

support_context = {"support_email": settings.SUPPORT_EMAIL}

urlpatterns = [
    path("", 
         TemplateView.as_view(template_name="pages/home.html",
                              extra_context={"recipe_count": Recipe.objects.count()}), 
         name="home"),
    path("about/", 
         TemplateView.as_view(template_name="pages/about.html"), 
         name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nnr.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),

    # Custom urls
    path("privacy/", TemplateView.as_view(template_name="privacy.html", 
                                          extra_context=support_context),
                    name="privacy"),
    path("support", TemplateView.as_view(template_name="support.html", 
                                         extra_context=support_context),
                    name="support"),
    path("tos/", TemplateView.as_view(template_name="tos.html", 
                                      extra_context=support_context),
                 name="tos"),
    path("main/", include("main.urls", namespace="main")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("recipes.urls", namespace="recipes")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main/urls.py
# included in config.urls with prefix "main"
from django.urls import include, path, register_converter
from django.views.generic import TemplateView

import main.views as views

app_name = "main"

urlpatterns = [
    path("public_key/", views.public_key, name="public_key"),
    path("webhook/", views.webhook, name="webhook"),
    path("create-checkout-session/", 
         views.create_checkout_session, 
         name="create_checkout_session"),
    path("success/", 
         views.checkout_success,
         name="checkout_success"),
    path("cancel_checkout/",
         TemplateView.as_view(template_name="main/cancel.html"),
         name="checkout_cancel"),
     path("payment/",
          views.payment,
          name="payment"),
     path("cancel_subscription/",
          views.cancel_subscription,
          name="cancel_subscription"),
     path("reactivate/",
          views.reactivate_subscription,
          name="reactivate_subscription"),
     path("expired/",
          TemplateView.as_view(template_name="main/expired.html"),
          name="expired"),
     path("processing/",
          TemplateView.as_view(template_name="main/processing.html"),
          name="processing"),
    ]

nnr/users/urls.py
from django.urls import path

from nnr.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

from main.views import (
    update_payment,
    confirm_payment
)

from recipes.views import (
    SavedRecipeList,
    SubmittedRecipeList,
    RatedRecipeList,
    UserTagList,
    UserTagDetail,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~update_payment",
        view=update_payment,
        name="update_payment"),
    path("~confirm_payment",
         view=confirm_payment, 
         name="confirm_payment"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/saved/", 
        view=SavedRecipeList.as_view(), 
        name="saved_recipes"),
    path("<str:username>/submitted/", 
        view=SubmittedRecipeList.as_view(), 
        name="submitted_recipes"),
    path("<str:username>/rated/",
        view=RatedRecipeList.as_view(),
        name="rated_recipes"),
    path("<str:username>/tagged/",
        view=UserTagList.as_view(),
        name="user_tags"),
    path("<str:username>/tagged/<str:tag_slug>/",
        view=UserTagDetail.as_view(),
        name="usertag_detail"),        

]

recipes/urls.py
# Recipes urls. Imported with no prefix
from django.urls import include, path, register_converter
import recipes.views as views
import recipes.converters as converters

app_name = "recipes"

register_converter(converters.LetterConverter, "letter")

recipe_urls = [
     path("browse", 
          view=views.RecipeList.as_view(),
          name="recipe_list"),
     path("add/",
          view=views.CreateRecipe.as_view(),
          name="recipe_create"),
     path("edit/<slug:slug>/",
          view=views.UpdateRecipe.as_view(),
          name="recipe_update"),
     path("delete/<slug:slug>/",
         view=views.DeleteRecipe.as_view(),
         name="recipe_delete"),         
     path("save/",
          view=views.SaveRecipe.as_view(),
          name="save_recipe"),         
     path("rate/",
          view=views.RateRecipe.as_view(),
          name="rate_recipe"),
     path("search/",
          view=views.SearchRecipes.as_view(),
          name="search_recipes"),
     path("<letter:first_letter>/",
          view=views.RecipeByLetterList.as_view(),
          name="letter_recipe"),
     path("<slug:slug>/",
          view=views.RecipeDetail.as_view(),
          name="recipe_detail"),         
]

tag_urls = [
     path("",
          view=views.TagList.as_view(),
          name="tag_list"),
     path("tagrecipe/",
          view=views.TagRecipe.as_view(),
          name="tag_recipe"),
     path("untag/",
          view=views.untag,
          name="untag"),
     path("all/",
          view=views.all_tags,
          name="get_all_tags"),
     path("<slug:slug>",
          view=views.TagDetail.as_view(),
          name="tag_detail"),
]

urlpatterns = [
    path("rotd/", 
          view=views.RecipeOfTheDay.as_view(),
          name="rotd"),
     path("home/",
          view=views.DashboardView.as_view(),
          name="home"),
    path("tags/", include(tag_urls)),
    path("", include(recipe_urls)),    
]

nnr/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

nnr/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

nnr/users/views.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

import stripe

from main.forms import CancelForm, ReactivateForm
User = get_user_model()

class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        
        context =  super().get_context_data(**kwargs)
        subs = None
        has_sub = not self.object.profile.subscription_status in ("admin", "free", "")
        if has_sub:
            stripe.api_key = settings.STRIPE_SK
            subs = stripe.Subscription.list(customer=self.object.profile.stripe_id)
        context["has_sub"] = has_sub
        if subs:
            context["cancel_at_period_end"] = subs.data[0].cancel_at_period_end
            end_date = datetime.fromtimestamp(subs.data[0].current_period_end)
            context["subscription_end"] = end_date.strftime("%B %d, %Y")
            context["amount"] = subs.data[0].plan.amount / 100
            context["cancel_form"] = CancelForm()
            context["reactivate_form"] = ReactivateForm()
        return context

user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]
    context_object_name = "user"

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

nnr/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}No Nonsense Recipes{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="recipes">
    <meta name="author" content="No Nonsense Recipes">
    
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' https://d1q0lpl7gly8q2.cloudfront.net https://api.nononsense.recipes; style-src 'self' https://d1q0lpl7gly8q2.cloudfront.net https://stackpath.bootstrapcdn.com; script-src 'self' https://d1q0lpl7gly8q2.cloudfront.net https://js.stripe.com https://checkout.stripe.com https://stackpath.bootstrapcdn.com https://code.jquery.com https://cdnjs.cloudflare.com https://api.nononsense.recipes; connect-src 'self' https://d1q0lpl7gly8q2.cloudfront.net https://api.stripe.com https://checkout.stripe.com https://api.nononsense.recipes; frame-src 'self' https://d1q0lpl7gly8q2.cloudfront.net https://js.stripe.com https://hooks.stripe.com https://checkout.stripe.com; img-src 'self' https://d1q0lpl7gly8q2.cloudfront.net https://*.stripe.com https://api.nononsense.recipes https://simpleanalyticsbadge.com;">
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <script src="https://js.stripe.com/v3/"></script>

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    
    {% block morecss %}
    {% endblock morecss %}

  </head>

  <body>
    <nav id="main-nav" class="navbar navbar-expand-md navbar-light bg-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
          <svg viewBox="0 0 30 30" xmlns="https://www.w3.org/2000/svg">
            <path stroke="rgba(0, 0, 0, 0.5)" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" d="M4 7h22M4 15h22M4 23h22"/>
          </svg>
        </span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'images/logos/SocialProfile/twitter-profilepicture-whitebg.png' %}"
              height="40px" width="40px" alt="No Nonsense Recipes" />
      </a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% if request.user.is_authenticated %}{% url 'recipes:home' %}{% else %}{% url 'home' %}{% endif %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:rotd' %}">Recipe of the Day</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:tag_list' %}">Tags</a>
          </li>            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:recipe_list' %}">Browse</a>
          </li>
          
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:recipe_create' %}">Add</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:search_recipes' %}">Search</a>
          </li>            
          {% else %}
          <span class="navbar-text ml-2 font-weight-bold text-dark">« Browse for free!</span>
          <li class="nav-item ml-5">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link btn btn-success text-light" href="{% url 'account_signup' %}">Start Your Free Trial</a>
          </li>            
          <span class="navbar-text ml-2 font-weight-bold text-dark">to search and save recipes (and more!)</span>
          {% endif %}
          </ul>
          <ul class="nav navbar-nav pull-xs-right">
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false" id="navbarDropdownMenuLink">
                  Hello {{ request.user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}">{% trans "Profile" %}</a>
                <a class="dropdown-item" href="{% url 'support' %}">{% trans "Support" %}</a>
                <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </div>
            </li>
          {% else %}
          

            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>            
          {% endif %}
        </ul>
      </div>
    </nav>

    {% if messages %}
    <div class="container" id="messages">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
        {% endfor %}
    </div>
    {% endif %}

    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

    

    <footer class="footer">
      <div class="container">
        <ul class="nav justify-content-center">
          <li class="nav-item text-muted mt-auto mb-auto">
            <small>©2020 KotsF LLC</small>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">
              <small>About</small>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tos' %}">
              <small>Terms of Service</small>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'privacy' %}">
              <small>Privacy Policy</small>
            </a>
          </li>
        </ul>
        
      </div>
    </footer>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

    {% block morejs %}
      
    {% endblock morejs %}
    <script async defer src="https://api.nononsense.recipes/app.js"></script>
    <noscript><img src="https://api.nononsense.recipes/image.gif" alt=""></noscript>
    
  </body>

  
</html>
 

nnr/templates/markdown_help.html
{% load static %}
<p class="text-muted">
    <a href="https://daringfireball.net/projects/markdown/">Markdown</a> may be used to format text. 
    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#markdownHelp">
        help
    </button>
</p>

<div class="modal fade" id="markdownHelp" tabindex="-1" role="dialog" aria-labelledby="markdownHelpTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="markdownHelpTitle">Markdown Help</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">

                    <div class="row mb-2">
                        <div class=col-sm-6>
                            <strong>Markdown Text</strong>
                        </div>
                        <div class="col-sm-6">
                            <strong>HTML</strong>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            *italics*
                        </div>
                        <div class="col-sm-6">
                            <em>italics</em>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            *bold*
                        </div>
                        <div class="col-sm-6">
                            <strong>bold</strong>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            [This is a link](http://thisisalink.com "link title")
                        </div>
                        <div class="col-sm-6">
                            <a href="http://thisisalink.com" title="link title">This is a link</a>
                        </div>
                    </div>                

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <pre>
Use two spaces at the end of a line  
for a line break                        
                            </pre>
                        </div>
                        <div class="col-sm-6">
                            Use two spaces at the end of a line <br>
                            for a line break
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <pre>
Use a blank space between paragraphs

for a paragraph break
                            </pre>
                        </div>
                        <div class="col-sm-6">
                            <p>Use a blank space between paragraphs.</p>
                            <p>for a paragraph break</p>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <pre>
#Heading1
##Heading2
###Heading3
                            </pre>
                        </div>
                        <div class="col-sm-6">
                            <h1>Heading1</h1>
                            <h2>Heading2</h2>
                            <h3>Heading3</h3>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <pre>
Ordered list: 
1. First item 
2. Second item
3. Third item 
                            </pre>
                        </div>
                        <div class="col-sm-6">
                            <ol>
                                <li>First item</li>
                                <li>Second item</li>
                                <li>Third item</li>
                            </ol>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <pre>
Unordered list: 
- First item 
- Second item
- Third item
                            </pre>
                        </div>
                        <div class="col-sm-6">
                            <ul>
                                <li>First item</li>
                                <li>Second item</li>
                                <li>Third item</li>
                            </ul>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <pre>
> Put a right angle bracket
at the start of each paragraph

> to create a blockquote.
                            </pre>
                        </div>
                        <div class="col-sm-6">
                            <blockquote>
                                <p>Put a right angle bracket at the start of each paragraph</p>
                                <p>to create a blockquote</p>
                            </blockquote>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

nnr/templates/support.html
{% extends "base.html" %}

{% block content %}
<div class="main-content">
    <h1>Support</h1>
    <p>Please email <a href="mailto:{{ support_email }}">{{ support_email }}</a>
    with any questions or feedback</p>
</div>
{% endblock content %}